import fs from 'node:fs/promises';
import path from 'node:path';

import { config } from 'dotenv';

import { createRendiClient } from '../src/lib/rendi/client';

// Load environment variables from .env.local
config({ path: path.join(process.cwd(), '.env.local') });

const RENDI_API_KEY = process.env.RENDI_API_KEY;

if (!RENDI_API_KEY) {
  console.error('Error: RENDI_API_KEY environment variable is not set');
  console.error('Please add RENDI_API_KEY to your .env.local file');
  process.exit(1);
}

const BROLL_PATH = path.join(process.cwd(), 'public/assets/reel-generator/video/bRoll.MOV');
const AUDIO_FOLDER = path.join(process.cwd(), 'public/assets/reel-generator/audio');

interface UploadResults {
  bRollFileId: string;
  audioFileIds: Record<string, string>;
}

async function uploadBRoll(client: ReturnType<typeof createRendiClient>): Promise<string> {
  console.log('\n📹 Uploading bRoll.MOV...');

  const stats = await fs.stat(BROLL_PATH);
  const fileSize = (stats.size / (1024 * 1024)).toFixed(2);

  console.log(`File size: ${fileSize} MB`);

  // Check if file is larger than 10MB (Rendi upload limit)
  if (stats.size > 10 * 1024 * 1024) {
    console.warn('⚠️  bRoll.MOV is too large for direct upload (>10MB)');
    console.warn('⚠️  You need to either:');
    console.warn('    1. Deploy your app and use the production URL');
    console.warn('    2. Upload to cloud storage (S3, etc.) and get a public URL');
    console.warn('    3. Use a file hosting service\n');
    console.warn('For now, skipping bRoll upload. You will need to manually set');
    console.warn('the bRollFileId after hosting the file publicly.\n');
    return 'PLACEHOLDER_BROLL_FILE_ID'; // Will need to be replaced manually
  }

  const buffer = await fs.readFile(BROLL_PATH);
  const result = await client.uploadFile(buffer, 'bRoll.MOV', 'video/quicktime');

  console.log(`✅ Uploaded: ${result.file_id}`);
  console.log(`   Storage URL: ${result.storage_url}`);

  return result.file_id;
}

async function uploadAudioFiles(
  client: ReturnType<typeof createRendiClient>,
): Promise<Record<string, string>> {
  console.log('\n🎵 Uploading audio files...');

  const files = await fs.readdir(AUDIO_FOLDER);

  const audioFiles = files.filter((file) => {
    const ext = path.extname(file).toLowerCase();
    return ['.mp3', '.wav', '.m4a', '.aac', '.ogg', '.flac'].includes(ext);
  });

  console.log(`Found ${audioFiles.length} audio files`);

  const audioFileIds: Record<string, string> = {};

  for (const audioFile of audioFiles) {
    const audioPath = path.join(AUDIO_FOLDER, audioFile);
    const buffer = await fs.readFile(audioPath);
    const fileSize = (buffer.length / 1024).toFixed(2);

    console.log(`\nUploading ${audioFile} (${fileSize} KB)...`);

    const result = await client.uploadFile(buffer, audioFile, 'audio/mpeg');

    audioFileIds[audioFile] = result.file_id;

    console.log(`✅ Uploaded: ${result.file_id}`);
  }

  return audioFileIds;
}

function generateConstantsCode(results: UploadResults): string {
  const audioFileIdsCode = Object.entries(results.audioFileIds)
    .map(([filename, fileId]) => `    '${filename}': '${fileId}',`)
    .join('\n');

  return `
// ============================================================================
// Rendi.dev Asset File IDs
// ============================================================================
// Generated by: npm run upload-rendi-assets
// Date: ${new Date().toISOString()}

export const RENDI_ASSETS = {
  bRollFileId: '${results.bRollFileId}',
  audioFileIds: {
${audioFileIdsCode}
  },
} as const;
`;
}

async function main() {
  console.log('🚀 Starting Rendi asset upload...\n');

  const client = createRendiClient(RENDI_API_KEY);

  try {
    // Upload bRoll video
    const bRollFileId = await uploadBRoll(client);

    // Upload all audio files
    const audioFileIds = await uploadAudioFiles(client);

    const results: UploadResults = {
      bRollFileId,
      audioFileIds,
    };

    // Generate constants code
    const constantsCode = generateConstantsCode(results);

    console.log('\n' + '='.repeat(80));
    console.log('✅ ALL UPLOADS COMPLETE');
    console.log('='.repeat(80));
    console.log('\nAdd this to src/lib/reel-generator/constants.ts:\n');
    console.log(constantsCode);
    console.log('\n' + '='.repeat(80));

    // Save to a file for easy copying
    const outputPath = path.join(process.cwd(), 'rendi-assets.output.txt');
    await fs.writeFile(outputPath, constantsCode);
    console.log(`\n📄 Constants code saved to: ${outputPath}`);
    console.log('='.repeat(80) + '\n');
  } catch (error) {
    console.error('\n❌ Upload failed:', error);
    process.exit(1);
  }
}

main();
